name: CI - Lint & Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: API deps
        run: |
          python -m pip install --upgrade pip
          if [ -f apps/api/requirements.txt ]; then pip install -r apps/api/requirements.txt; fi

      - name: Python lint (ruff optional)
        run: |
          echo "TODO: add ruff or flake8"; python -c "print('lint placeholder')"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Web deps
        run: |
          cd apps/web || exit 0
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install

      - name: Web build
        run: |
          cd apps/web || exit 0
          pnpm run build || echo 'skip build if no web'
