name: Release
on:
  push:
    tags: [ "v*.*.*" ]
  workflow_dispatch:

jobs:
  release_api:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for git log
      - name: Generate Release Notes
        run: |
          git fetch --prune --unshallow --tags || true
          latest_tag=$(git describe --tags --abbrev=0 || echo "")
          if [ -z "$latest_tag" ]; then range=""; else range="$latest_tag..HEAD"; fi
          git log --pretty=format:"* %h %s" $range > CHANGELOG_PART.md
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          body_path: CHANGELOG_PART.md
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  release_web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Web
        working-directory: apps/web
        run: |
          npm ci
          npm run build
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

  notify_slack:
    runs-on: ubuntu-latest
    needs: [release_api, release_web]
    if: success()
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'Release Bot'
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_COLOR: '#36a64f'
          SLACK_MESSAGE: '🚀 New release ${{ github.ref_name }} deployed successfully to Render and Vercel!'

